variables:
    DEV: "Rowland Ogwara"
stages:
    - test
    - deploy

test:
    stage: test
    script:
        - mvn clean test

deploy:
    stage: deploy
    script:
        - mvn clean deploy -Dtest.skip=true
        - mv target/generated-docs public
    environment: prod
    artifacts:
        paths:
            - public
    only:
        - master
        - develop