variables:
    DEV: "Rowland Ogwara"
stages:
    - test
    - deploy

test:
    stage: test
    script:
        - mvn clean test

deploy:
    stage: deploy
    script:
        - mvn deploy -Dmaven.test.skip=true
    environment: prod
    only:
        - master
        - development